chore(LT-5845): [MarginTrading.Activities] Update MessagePack to 2.x …
LykkeBusiness/MarginTrading.Activities pull request #122
Opened 2024-10-28 08:44 UTC by lykke-vashetsin

…version

2024-11-05 13:44 UTC, tarurar requested changes

2024-11-05 13:44 UTC, tarurar commented on Directory.Packages.props
> +    <PackageVersion Include="MessagePack" Version="2.5.187" />
You probably do not need direct dependency on MessagePack.

2024-11-05 19:55 UTC, lykke-vashetsin commented on Directory.Packages.props
> +    <PackageVersion Include="MessagePack" Version="2.5.187" />
didn't work

2024-11-11 07:58 UTC, tarurar submitted a review, later dismissed

2024-11-11 10:44 UTC, tarurar approved these changes

2024-11-11 10:49 UTC, merged